### ISSUE TITLE
Error when uploading track

### ISSUE THREAD

**Issue by simonv3** [funmusicplace/mirlo#221]
```
users/3/tracks/75/audio TypeError: Cannot read properties of undefined (reading 'path')
Nov 10 09:59:36 AM      at /opt/render/project/src/src/utils/file.ts:24:34
Nov 10 09:59:36 AM      at step (/opt/render/project/src/src/utils/file.ts:33:23)
Nov 10 09:59:36 AM      at Object.next (/opt/render/project/src/src/utils/file.ts:14:53)
Nov 10 09:59:36 AM      at /opt/render/project/src/src/utils/file.ts:8:71
Nov 10 09:59:36 AM      at new Promise (<anonymous>)
Nov 10 09:59:36 AM      at __awaiter (/opt/render/project/src/src/utils/file.ts:4:12)
Nov 10 09:59:36 AM      at checkFileType (/opt/render/project/src/src/utils/file.ts:22:18)
Nov 10 09:59:36 AM      at /opt/render/project/src/src/utils/processTrackAudio.ts:102:41
Nov 10 09:59:36 AM      at step (/opt/render/project/src/src/utils/processTrackAudio.ts:33:23)
Nov 10 09:59:36 AM      at Object.next (/opt/render/project/src/src/utils/processTrackAudio.ts:14:53)
Nov 10 09:59:36 AM      at /opt/render/project/src/src/utils/processTrackAudio.ts:8:71
Nov 10 09:59:36 AM      at new Promise (<anonymous>)
Nov 10 09:59:36 AM      at __awaiter (/opt/render/project/src/src/utils/processTrackAudio.ts:4:12)
Nov 10 09:59:36 AM      at /opt/render/project/src/src/utils/processTrackAudio.ts:101:43
Nov 10 09:59:36 AM      at /opt/render/project/src/src/routers/v1/users/{userId}/tracks/{trackId}/audio.ts:54:54
Nov 10 09:59:36 AM      at step (/opt/render/project/src/src/routers/v1/users/{userId}/tracks/{trackId}/audio.ts:33:23)
```

**Comment by simonv3** [comment]
This function isn't used an ymore in `processTrackAudio`, closing for now
