### ISSUE TITLE
ffmpeg error when uploading tracks

### ISSUE THREAD

**Issue by superaarhus** [funmusicplace/mirlo#934]
When uploading audio track.  After browse for file. 
This is seems to be the route that is triggering the error

`/v1/manage/tracks/{}/audio
`
```
blackbird-background  | error: Error converting to hls: ffmpeg exited with code 127 {"service":"background-queue"}
blackbird-background  | error: Error creating audio folder ffmpeg exited with code 127 {"service":"background-queue","stack":"Error: ffmpeg exited with code 127\n    at ChildProcess.<anonymous> (/var/www/api/node_modules/fluent-ffmpeg/lib/processor.js:182:22)\n    at ChildProcess.emit (node:events:517:28)\n    at ChildProcess.emit (node:domain:489:12)\n    at Process.ChildProcess._handle.onexit (node:internal/child_process:292:12)"}
blackbird-background  | info: completed:upload-audio {"service":"background-queue"}
blackbird-api         | info: Job with id "2" has been completed, {"error":{"stack":"Error: ffmpeg exited with code 127\n    at ChildProcess.<anonymous> (/var/www/api/node_modules/fluent-ffmpeg/lib/processor.js:182:22)\n    at ChildProcess.emit (node:events:517:28)\n    at ChildProcess.emit (node:domain:489:12)\n    at Process.ChildProcess._handle.onexit (node:internal/child_process:292:12)","message":"ffmpeg exited with code 127"}} {"service":"api"}
blackbird-api         | There was an error processing the job
```

**Comment by superaarhus** [comment]
Did some more digging.  The issue is caused by the ffmpeg in the my path doesn't have libfdkaac compile.  

Would think that 

 `jrottenberg/ffmpeg:5.1-ubuntu2204` 

has that handled.  I would imagine that is the version of ffmpeg that the fluent-ffmpeg would be using.

I have recompiled my ffmepg with lib_fdk_aac, and that seems to fix the ffmpeg issue.

**Comment by simonv3** [comment]
Yeah this is strange, this is just with the normal `docker compose watch` setup?
